repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        name: markdownlint
        entry: markdownlint
        language: node
        types_or:
          - markdown
        additional_dependencies: []
        args:
          - --ignore
          - node_modules
          - --ignore
          - .venv

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-zero
        files: ^(backend/src|scripts)/
